todoapp/apps/manager/urls.py
from django.conf.urls import patterns, include, url



urlpatterns = patterns('todoapp.apps.manager.views',
    url(r'^$','index',name='index'),
    url(r'^lists/(?P<list_id>\d+)/$','view_list',name='view_list'),
    url(r'^lists/(?P<list_id>\d+)/add_task/$','add_task',name='add_task'),
    url(r'^lists/(?P<list_id>\d+)/update_task/$','update_task',name='update_task'),
    url(r'^lists/new/$','new_list',name='new_list'),
    url(r'^lists/(?P<list_id>\d+)/monthly/','monthly_view_list',name='monthly_view_list'),
    url(r'^lists/(?P<list_id>\d+)/weekly/','weekly_view_list',name='weekly_view_list'),
    url(r'^task/(?P<task_id>\d+)/date_change/','date_change',name='date_change'),

)

todoapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

admin.site.site_header="Administration"

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'todoapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('todoapp.apps.manager.urls')),
    url(r'^user/',include('todoapp.apps.account.urls')),
)

todoapp/apps/manager/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.db.models import Q

class List(models.Model):
	user=models.ForeignKey(User,blank=True,null=True,related_name='list')

	def update_tasks_with_latest_date(self,latest_date):
		queryQ=Q()
		queryQ.add(Q(start_date__lt=latest_date) & Q(Q(canceled=False) & Q(completed=False)),Q.AND)
		tasks=self.tasks.filter(queryQ)

		for t in tasks:
			if t.start_date!=t.end_date:
				continue
			t.start_date=latest_date
			t.end_date=latest_date
			t.save()


	
class Task(models.Model):
	TYPE=(
		(1,'Every day'),
		(7,'Every week'),
		(30,'Every month'),
	)
	note = models.TextField(default='')
	list=models.ForeignKey(List,default=None,related_name='tasks',blank=True,null=True)

	freq=models.IntegerField(default=1,choices=TYPE)
	start_date=models.DateField()
	end_date=models.DateField()
	created_date=models.DateField()
	last_completed=models.DateField(blank=True, null=True)
	completed=models.BooleanField(default=False)
	canceled=models.BooleanField(default=False)


	def save(self,*args,**kwargs):
		if not self.id:
			now=date.today()
			self.start_date=now
			self.end_date=now
			self.created_date=now
			self.completed=False
			self.canceled=False
		if self.completed or self.canceled:
			self.last_completed=date.today()
		super(Task,self).save()

todoapp/apps/manager/forms.py
from django import forms
from django.forms import widgets
from todoapp.apps.manager.models import *
from django.forms.models import BaseModelFormSet
from django.utils.functional import curry


class DateSelectorWidget(widgets.MultiWidget):
    def __init__(self, attrs=None,years=None,days=None):
        MONTHS = {
            1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr',
            5:'May', 6:'Jun', 7:'Jul', 8:'Aug',
            9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'
            }

        
        try :
            years = [(year, year) for year in years]
            days = [(d, dd) for d,dd in days]
            months = [(month, MONTHS[month]) for month in range(1,13)]
        except ValueError:
            return ''

        _widgets = (
            widgets.Select(attrs=None, choices=years),
            widgets.Select(attrs=None, choices=months),
            widgets.Select(attrs=None,choices=days),
        )
        super(DateSelectorWidget, self).__init__(_widgets, attrs)

    def decompress(self, value):
        try:
            if value:
                return [value.year,value.month,value.day]
            return [None, None, None]
        except AttributeError:
            dt = [int(x) for x in value.split("-")]
            return [dt[0],dt[1],dt[2]]


    def format_output(self, rendered_widgets):
        widget_context={'year':rendered_widgets[0],'month':rendered_widgets[1],'week':rendered_widgets[2]}
        return u''.join(rendered_widgets)

    def value_from_datadict(self, data, files, name):
        datelist = [
            widget.value_from_datadict(data, files, name + '_%s' % i)
            for i, widget in enumerate(self.widgets)]
        try:
            D = date(day=int(datelist[2]), month=int(datelist[1]),
                    year=int(datelist[0]))
        except ValueError:
            return ''
        else:
            return str(D)

class MyModelFormsetBase(BaseModelFormSet):
    extra_args=None
    def __init__(self,*args,**kwargs):
        self.extra_args=kwargs.pop('extra_args',None)
        subFormClass = self.form
        self.form = curry(subFormClass,extra_args=self.extra_args)
        super(MyModelFormsetBase,self).__init__(*args,**kwargs)


class TaskCheckForm(forms.ModelForm):
    class Meta:
        model = Task
        fields=('completed','canceled')

    def __init__(self,*args,**kwargs):
        self.task = kwargs.get('instance', None)
        self.extra_args=kwargs.pop('extra_args',None)

        super(TaskCheckForm,self).__init__(*args,**kwargs)
        self.fields['completed'].widget.attrs['onchange'] = 'this.form.submit();'
        self.fields['canceled'].widget.attrs['onchange'] = 'this.form.submit();'


class DateChangeForm(forms.ModelForm):
    recurring=forms.BooleanField(required=False)
    class Meta:
        model=Task
        fields=('start_date','end_date','freq',)
    def __init__(self, *args, **kwargs):
        self.extra_args=kwargs.pop('extra_args',{})
        super(DateChangeForm,self).__init__(*args,**kwargs)
        self.fields['start_date'].required=False
        self.fields['end_date'].required=False




    def clean(self):
        cleaned_data=self.cleaned_data
        sd=cleaned_data.get('start_date')
        ed=cleaned_data.get('end_date')
        r=cleaned_data.get('recurring')
        if r and sd and ed and (ed-sd).days<0:
            raise forms.ValidationError('Dates must be in chronological order.')
        if sd==None or (r and ed==None):
            raise forms.ValidationError('Dates must be given.')
        return cleaned_data

    def save(self):
        task=super(DateChangeForm,self).save(commit=False)
        r=self.cleaned_data['recurring']
        task.completed=False
        task.canceled=False
        if r:
            task.start_date=self.cleaned_data['start_date']
            task.end_date=self.cleaned_data['end_date']

        else:
            task.start_date=self.cleaned_data['start_date']
            task.end_date=self.cleaned_data['start_date']
        task.save()
        return task

todoapp/apps/manager/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseBadRequest
from todoapp.apps.manager.models import *
from todoapp.apps.manager.forms import *
from django.core.urlresolvers import reverse
from datetime import date
from datetime import datetime
from django.http import Http404
from django.forms.models import modelformset_factory
from django.db.models import Q,F
import calendar
from dateutil.relativedelta import relativedelta
from django.template.loader import render_to_string
import json
from django.core.exceptions import ObjectDoesNotExist


def perdelta(start,end,delta):
	cur=start
	while cur <= end:
		yield cur
		cur=cur+delta



def index(request):
	if request.user.is_authenticated():
		list_=request.user.list.first()
		if list_==None:
			list_=List.objects.create(user=request.user)
		return HttpResponseRedirect('/lists/%d/' % (list_.id,))
	return render(request,'manager/index.html',{'title':'home',})

def view_list(request,list_id):
	try:
		list_=List.objects.get(id=list_id)
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404

	today=date.today()
	list_.update_tasks_with_latest_date(today)


	queryQ=Q()
	queryQ.add(Q(start_date=today),Q.AND)

	objs=[]
	for t in list_.tasks.filter(Q(end_date__gt=F('start_date')) & Q(Q(canceled=False) & Q(completed=False))):
		tmpd=perdelta(t.start_date,t.end_date,relativedelta(days=t.freq))
		if today in tmpd:
			objs.append(t)
	queryQ.add(Q(id__in=[c.id for c in objs]),Q.OR)
	tasks=list_.tasks.filter(queryQ).order_by('id')

	fset=modelformset_factory(Task,formset=MyModelFormsetBase,form=TaskCheckForm,extra=0)
	forms=fset(queryset=tasks)
	
	return render(request,'manager/daily_list.html',{'title':'view list','list':list_,'today':today,'forms':forms})


def monthly_view_list(request,list_id):
	try:
		list_=List.objects.get(id=list_id)
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404

	today=date.today()
	cal=calendar.Calendar()
	days=cal.itermonthdays(today.year,today.month)
	output=[[]]
	week=0

	list_.update_tasks_with_latest_date(today)

	for day in days:
		tasks = current = False
		if day:

			d=date(today.year,today.month,day)

			queryQ=Q()
			queryQ.add(Q(start_date=d),Q.AND)

			objs=[]
			for t in list_.tasks.filter(Q(end_date__gt=F('start_date')) & Q(Q(canceled=False) & Q(completed=False))):
				tmpd=perdelta(t.start_date,t.end_date,relativedelta(days=t.freq))
				if d in tmpd:
					objs.append(t)
			queryQ.add(Q(id__in=[c.id for c in objs]),Q.OR)
			tasks=list_.tasks.filter(queryQ).order_by('id')



			if day==today.day:
				current=True
		output[week].append((day,tasks,current))
		if len(output[week])==7:
			output.append([])
			week=week+1

	return render(request,'manager/monthly_list.html',{'title':'view list','list':list_,'today':today,'output':output})




def weekly_view_list(request,list_id):
	try:
		list_=List.objects.get(id=list_id)
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404

	today=date.today()
	theday=calendar.weekday(today.year,today.month,today.day)
	firstday=today-relativedelta(days=theday)

	output=[]
	list_.update_tasks_with_latest_date(today)

	for i in range(0,7):
		tasks=current=False
		delta=relativedelta(days=i)
		day=firstday+delta

		queryQ=Q()
		queryQ.add(Q(start_date=day),Q.AND)

		objs=[]
		for t in list_.tasks.filter(Q(end_date__gt=F('start_date')) & Q(Q(canceled=False) & Q(completed=False))):
			tmpd=perdelta(t.start_date,t.end_date,relativedelta(days=t.freq))
			if day in tmpd:
				objs.append(t)
		queryQ.add(Q(id__in=[c.id for c in objs]),Q.OR)
		tasks=list_.tasks.filter(queryQ).order_by('id')




		if day==today:
			current=True
		output.append((day,tasks,current))

	return render(request,'manager/weekly_list.html',{'title':'view list','list':list_,'today':today,'output':output})



def add_task(request,list_id):
	try:
		list_=List.objects.get(id=list_id)
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404
	list_ = List.objects.get(id=list_id)
	new_item_text = request.POST['item_text']
	task=Task()
	task.note=new_item_text
	task.list=list_
	task.save()
	return HttpResponseRedirect('/lists/%d/' % (list_.id,))

def update_task(request,list_id):
	try:
		list_=List.objects.get(id=list_id)
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404

	fset=modelformset_factory(Task,formset=MyModelFormsetBase,form=TaskCheckForm,extra=0)

	if request.method=='POST':
		forms=fset(request.POST)
		if forms.is_valid():
			for f in forms:
				f.save()
	return HttpResponseRedirect('/lists/%d/' % (list_.id,))

def new_list(request):
	list_=List.objects.create()
	new_item_text = request.POST['item_text']
	task=Task()
	task.note=new_item_text
	task.list=list_
	task.save()
	return HttpResponseRedirect('/lists/%d/' % (list_.id,))

def date_change(request,task_id):
	try:
		task_=Task.objects.get(id=task_id)
		list_=task_.list
	except ObjectDoesNotExist:
		raise Http404
	if list_.user!=None and list_.user!=request.user:
		raise Http404

	if request.method=="POST":
		form=DateChangeForm(request.POST,instance=task_)
		if form.is_valid():
			form.save()
			return HttpResponse(json.dumps("OK"))
		else:
			errors={}
			errors["non_field_errors"]="<br />".join(form.non_field_errors())
			return HttpResponseBadRequest(json.dumps(errors))
		
	else:
		form=DateChangeForm(instance=task_)
	return render(request,'manager/datepicker.html',{'form':form,})

todoapp/apps/manager/templates/manager/daily_list.html
{% extends 'manager/list.html' %}
{% block list_content %}
{% load staticfiles %}


<script type="text/javascript">

$(document).ready(function(){

	function showTooltip(btn){
		var root = $(btn).closest('form');
		var tr = $(btn).closest('tr');
		var id=$(tr).attr('v');

		var parent=$(btn).parent();
		parent.css('position','relative');
		var base=$('<div>');
		base.addClass('sub');
		var content=$('<div>');
		base.css('position','absolute');
		base.css('top','-205px');
		base.css('left','-60px');
		base.css('background','#ccc');
		base.css('width','300px');
		base.css('padding','10px 0px 10px 10px');
		base.css('box-shadow','3px 3px 3px 0px gray');

		content.css('height','160px');
		content.css('overflow-y','auto');
		content.css('color','#000');

		
		var pointer=$('<div>');

		pointer.css('border','5px solid transparent');
		pointer.css('border-top-color','#ccc');
		pointer.css('position','absolute');
		pointer.css('top','205px');
		pointer.css('left','100px');

		var img_p=$('<p>');
		var img=$('<img>');
		img.attr('src',"{% static 'image/btn_exit.png' %}");
		img.css('cursor','pointer');
		img_p.append(img)
		img_p.css('text-align','right');
		img_p.css('padding','0 5px 0 0');
		img_p.css('margin','0');

		var img_loader=$('<img>');
		img_loader.attr('src',"{% static 'image/ajax-loader.gif' %}")

		base.append(img_p);
		base.append(content);
		base.append(pointer);
		parent.append(base);

		img_p.click(function(e){
			$(tr).find('.sub').remove();
			return false;
		});
		var wrap_div=$('<div>');
		var loder_p=$('<p>');
		loder_p.append(img_loader);
		loder_p.css('text-align','center');
		wrap_div.append(loder_p);

		$.ajax({
			url: "/task/"+id+"/date_change/",
			data: {
				csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			type: 'GET',
			dataType: 'html',
			cache: false,
			success: function(response) {
				loder_p.remove();
				wrap_div.html(response);

			},
			error: function(xhr,errmsg,err) {
				
			},
			complete: function() {
			}
		});
		content.html(wrap_div);



		return false;
	}

	$(".load").click(function(e){
		return showTooltip(this);
	});


});
</script>


	<div>
		<h2 class="title">My To-Do list {{today | date:'m/d/Y'}}</h2>
		<form method="POST" action="/lists/{{list.id}}/add_task/">
			{% csrf_token %}
			<input name="item_text" id="id_new_item" placeholder="Enter your To-Do" />
		</form>

		<ul id="view_tab" class="clearfix">
			<li class="bold"><a href="{% url 'view_list' list.id %}">Daily</a></li>
			<li class="lline"><a href="{% url 'weekly_view_list' list.id %}">Weekly</a></li>
			<li class="lline"><a href="{% url 'monthly_view_list' list.id %}">Monthly</a></li>
		</ul>

		{% if forms|length > 0 %}
		<form method="POST" action="/lists/{{list.id}}/update_task/">
		{% csrf_token %}
		{{forms.management_form}}
		
		<table id="id_list_table">
			<tr><th></th><th width="10%">Re-Sche</th><th width="10%">Cancel</th><th width="10%">Done</th></tr>
			{% for form in forms %}
			<tr v="{{form.task.id}}"><td>{{ forloop.counter }}: {{form.task.note}}</td><td style="text-align:center;"><a class="load" href=""><img src="{% static 'image/reschedu.png' %}" /></a></td><td>{{form.id}}{{form.canceled}}</td><td>{{form.completed}}</td></tr>
			{% endfor %}
		</table>
		</form>
		{% else %}
		<p>You are all done, today!</p>
		{% endif %}

	</div>
</div>
{% endblock %}

todoapp/apps/manager/templates/manager/datepicker.html
<style type="text/css">
div.ui-datepicker {
	font-size: 62%;
}
</style>
<script type="text/javascript">
<!--
$(document).ready(function(){
	function block_form(){
		$("select").attr('disabled','disabled');
		$("input").attr('disabled','disabled');
	}
	function unblock_form(){
		$("select").removeAttr('disabled');
		$("input").removeAttr('disabled');
		$("#form_ajax_error").find(".errorlist").remove();
		$("#form_ajax_error").hide();

	}
	function updateTask(target){

		var root = $(target).closest('form');
		var ul = $(root).find('ul');
		var id='{{form.instance.id}}';
		var data = {};

		$(ul).children().children().each(function(){
			if($(this).attr('name')){
				var name = $(this).attr('name');

				if($(this).attr('type') == 'checkbox' ){
					data[name]=$(this).prop('checked');
				}
				else{
					data[name]=$(this).val();
				}
				
			}
		});
		data['csrfmiddlewaretoken']='{{ csrf_token }}'
		console.log(data)
		block_form();
		

		$.ajax({
			url: "/task/"+id+"/date_change/",
			data: data,
			type: 'POST',
			dataType: 'json',
			cache: false,
			success: function(response) {
				unblock_form();
				console.log(response);
				window.location.reload();
							
			},
			error: function(errmsg) {
				unblock_form();
				var errors = JSON.parse(errmsg.responseText);
				var p=$('<p class="errorlist">');
				p.html(errors['non_field_errors']);
				$("#form_ajax_error").append(p);
				$("#form_ajax_error").show();
				console.log(errmsg.responseText);
				//window.location.reload();
				
			},
			complete: function() {
			
			}
		});


	}

	$("#id_start_date").datepicker();
	$("#id_end_date").datepicker();
	$("#id_datechanger li.d").hide();
	$("#id_recurring").click(function(e){
		var c=$(this).prop('checked');
		var ul = $(e.target).closest('ul');
		if(c){
			ul.children(".d").show();
		}
		else{
			ul.children(".d").hide();
		}
	});
	$("#id_datechanger").on('submit',function(e){
		e.preventDefault();
		updateTask(e.target);
	});
});

-->
</script>

<div>
	<form id="id_datechanger" method="post">
		{% csrf_token %}
		<ul>
		<li id="form_ajax_error" style="display:none;" class="bold"></li>
		<li><span>Date</span>{{form.start_date}}</li>
		<li><span>Recurring</span>{{form.recurring}}</li>
		<li class="d"><span>To date</span>{{form.end_date}}</li>
		<li class="d"><span>Repeat</span>{{form.freq}}</li>
		</ul>
		<input type="submit" name="save" value="save" />

	</form>
<div>

todoapp/apps/manager/templates/manager/index.html
{% extends 'base.html' %}
{% block title %}To-Do lists{% endblock %}
{% block content %}
<div id="content">
	<div>
		{% include 'user-info.html' %}
	</div>
	{% if messages %}
		<ul class="messages">
		{% for message in messages %}
			<li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
		{% endfor %}
		</ul>
	{% endif %}
	<div>
		<h2 class="title">Start a new To-Do list</h2>
		<form method="POST" action="/lists/new/">
			{% csrf_token %}
			<input name="item_text" id="id_new_item" placeholder="Enter your To-Do" />
		</form>

	</div>
</div>
{% endblock %}

todoapp/apps/manager/templates/manager/list.html
{% extends 'base.html' %}
{% block title %}To-Do lists{% endblock %}
{% block content %}

<script type="text/javascript">
<!--
$(document).ready(function(){
	function block_form(){
		$("select").attr('disabled','disabled');
		$("input").attr('disabled','disabled');
	}
	function unblock_form(){
		$("select").removeAttr('disabled');
		$("input").removeAttr('disabled');

	}
	function updateTask(target){

		var root = $(target).closest('form');
		var tr = $(target).closest('tr');
		var id=$(tr).attr('v');
		var data = {};

		$(tr).children().children().each(function(){
			if($(this).attr('name')){
				var name = $(this).attr('name');

				if($(this).attr('type') == 'checkbox' ){
					data[name]=$(this).prop('checked');
				}
				
			}
		});
		data['csrfmiddlewaretoken']='{{ csrf_token }}'
		block_form();
		

		$.ajax({
			url: "/ajax/"+id+"/update_task/",
			data: data,
			type: 'POST',
			dataType: 'text',
			cache: false,
			success: function(response) {
				unblock_form();
				console.log(response);
				window.location.reload();
							
			},
			error: function(errmsg) {
				unblock_form();
				console.log(errmsg.responseText);
				window.location.reload();
				
			},
			complete: function() {
			
			}
		});


	}
	/*
	$("#id_list_table tr td input").on('click',function(e){

		updateTask(e.target);
	});*/

});

-->
</script>
<div id="content">
	<div>
		{% include 'user-info.html' %}
	</div>
	{% if messages %}
		<ul class="messages">
		{% for message in messages %}
			<li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
		{% endfor %}
		</ul>
	{% endif %}

	{% block list_content %}{% endblock %}
</div>
{% endblock %}

todoapp/apps/manager/templates/manager/monthly_list.html
{% extends 'manager/list.html' %}
{% block list_content %}
	<div>
		<h2 class="title">My To-Do list {{today | date:'m/d/Y'}}</h2>
		<form method="POST" action="/lists/{{list.id}}/add_task/">
			{% csrf_token %}
			<input name="item_text" id="id_new_item" placeholder="Enter your To-Do" />
		</form>

		<ul id="view_tab" class="clearfix">
			<li class=""><a href="{% url 'view_list' list.id %}">Daily</a></li>
			<li class="lline"><a href="{% url 'weekly_view_list' list.id %}">Weekly</a></li>
			<li class="bold lline"><a href="{% url 'monthly_view_list' list.id %}">Monthly</a></li>
		</ul>
		<p class="center bold">{{today | date:'F Y'}}</p>
		<table id="id_list_table">
			<tr>
				<th>Mon.</th>
				<th>Tue.</th>
				<th>Wed.</th>
				<th>Thu.</th>
				<th>Fri.</th>
				<th>Sat.</th>
				<th>Sun.</th>
			</tr>
			{% for week in output %}
			<tr>
			{% for day,tasks,current in week %}
				<td class={% if day == 0 %}"empty"{% endif %}{% if day != 0 and not current %}"day"{% endif %}
				{% if day != 0 and current %}"current"{% endif %}>
				{% if day != 0 %}<span class="italic">{{day}}</span>
				{% for task in tasks %}
				<br />
				<span class="bold">{{ forloop.counter }}: </span>{{task.note}}
				{% endfor %}
				{% endif %}
				</td>
			{% endfor %}
			</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

todoapp/apps/manager/templates/manager/task.html
{% extends 'base.html' %}
{% block title %}To-Do lists{% endblock %}
{% block content %}

<style type="text/css">
div.ui-datepicker {
	font-size: 62%;
}
</style>
<script type="text/javascript">
<!--
$(document).ready(function(){
	function block_form(){
		$("select").attr('disabled','disabled');
		$("input").attr('disabled','disabled');
	}
	function unblock_form(){
		$("select").removeAttr('disabled');
		$("input").removeAttr('disabled');
		$("#form_ajax_error").find(".errorlist").remove();
		$("#form_ajax_error").hide();

	}
	function updateTask(target){

		var root = $(target).closest('form');
		var ul = $(root).find('ul');
		var id='{{form.instance.id}}';
		var data = {};

		$(ul).children().children().each(function(){
			if($(this).attr('name')){
				var name = $(this).attr('name');

				if($(this).attr('type') == 'checkbox' ){
					data[name]=$(this).prop('checked');
				}
				else{
					data[name]=$(this).val();
				}
				
			}
		});
		data['csrfmiddlewaretoken']='{{ csrf_token }}'
		console.log(data)
		block_form();
		

		$.ajax({
			url: "/task/"+id+"/date_change/",
			data: data,
			type: 'POST',
			dataType: 'json',
			cache: false,
			success: function(response) {
				unblock_form();
				console.log(response);
				//window.location.reload();
							
			},
			error: function(errmsg) {
				unblock_form();
				var errors = JSON.parse(errmsg.responseText);
				var p=$('<p class="errorlist">');
				p.html(errors['non_field_errors']);
				$("#form_ajax_error").append(p);
				$("#form_ajax_error").show();
				console.log(errmsg.responseText);
				//window.location.reload();
				
			},
			complete: function() {
			
			}
		});


	}

	$("#id_start_date").datepicker();
	$("#id_end_date").datepicker();
	$("#id_datechanger li.d").hide();
	$("#id_recurring").click(function(e){
		var c=$(this).prop('checked');
		var ul = $(e.target).closest('ul');
		if(c){
			ul.children(".d").show();
		}
		else{
			ul.children(".d").hide();
		}
	});
	//$("#id_datechanger").on('submit',function(e){
		//e.preventDefault();
		//updateTask(e.target);
	//});
});

-->
</script>

<div id="content">
	<div>
		{% include 'user-info.html' %}
	</div>
	{% if messages %}
		<ul class="messages">
		{% for message in messages %}
			<li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
		{% endfor %}
		</ul>
	{% endif %}
	<div>
	<form id="id_datechanger" method="post" action="{% url 'date_change' task_id %">
		{% csrf_token %}
		<ul>
		<li><span>Date</span>{{form.start_date}}</li>
		<li><span>Recurring</span>{{form.recurring}}</li>
		<li class="d"><span>To date</span>{{form.end_date}}</li>
		<li class="d"><span>Repeat</span>{{form.freq}}</li>
		</ul>
		<input type="submit" name="save" value="save" />
	</form>
	<div>
	</div>
{% endblock %}

todoapp/apps/manager/templates/manager/weekly_list.html
{% extends 'manager/list.html' %}
{% block list_content %}
	<div>
		<h2 class="title">My To-Do list {{today | date:'m/d/Y'}}</h2>
		<form method="POST" action="/lists/{{list.id}}/add_task/">
			{% csrf_token %}
			<input name="item_text" id="id_new_item" placeholder="Enter your To-Do" />
		</form>

		<ul id="view_tab" class="clearfix">
			<li class=""><a href="{% url 'view_list' list.id %}">Daily</a></li>
			<li class="bold lline"><a href="{% url 'weekly_view_list' list.id %}">Weekly</a></li>
			<li class="lline"><a href="{% url 'monthly_view_list' list.id %}">Monthly</a></li>
		</ul>
		<table id="id_list_table">
			<tr>
				{% for day,tasks,current in output %}
				<th>{{day | date:'l, M j'}}</th>
				{% endfor %}
			</tr>
			<tr>
				{% for day,tasks,current in output %}
				<td class={% if not current %}"day"{% endif %}
				{% if current %}"current"{% endif %}>
				{% for task in tasks %}
				<span class="bold">{{ forloop.counter }}: </span>{{task.note}}<br />
				{% endfor %}
				</td>
				{% endfor %}
			</tr>
		</table>
	</div>
</div>
{% endblock %}